version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ownapipro
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
